spring:
  profiles:
    active: @spring.profiles.active@

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/amigoscodedemo
    username: postgres
    password: 123456789
    pool-size: 30